name: magnit_crm
description: CRM for CView

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  uuid: ^4.1.0
  flutter_svg: ^2.0.7
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  flutter_native_splash: ^2.3.4
  extended_masked_text: ^2.3.1
  masked_text_field: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

